name:  terraform github actions
on:
  push:
    paths:
      - "aws/**"
    branches:
      - "master"
env:
  AWS_REGION:  ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  terraform:
    name: terraform
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Terraform Init
        run: terraform -chdir=aws init 
        continue-on-error: false
      
      - name: Terraform Validate
        id: validate
        run: terraform -chdir=aws validate -no-color

      - name: Terraform Plan
        run: terraform -chdir=aws plan 
        continue-on-error: false

      - name: Terraform Apply
        run: terraform -chdir=aws apply
        continue-on-error: false
