name:  terraform github actions
on:

  push:
    paths:
      - "aws/**"
    branches:
      - "master"
jobs:
  terraform:
    name: terraform
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2

      - run: terraform -chdir=aws init 
        continue-on-error: false

      - run: terraform -chdir=aws plan 
        continue-on-error: false