name:  terraform github actions
on:

  push:
    paths:
      - "aws"
    branches:
      - "master"
jobs:
  terraform:
    name: terraform
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3

  